### ISSUE TITLE
how to integrate it with FOSUserBundle?

### ISSUE THREAD

**Issue by napestershine** [Yosimitso/WorkingForumBundle#1]

**Comment by Yosimitso** [comment]
There's nothing to do, because the bundle use your user's entity which extends fosuserbundle.

**Comment by napestershine** [comment]
@Yosimitso  Thanks so much.

I am talking about this step:

Your User Entity needs to extends : \Yosimitso\WorkingForumBundle\Entity\User Example :

   class User extends \Yosimitso\WorkingForumBundle\Entity\User
{
    // YOUR ENTITY
}

**Comment by Yosimitso** [comment]
I think i get it, if you can't extend the mapped superclass (\Yosimitso\WorkingForumBundle\Entity\User) just implements the interface \Yosimitso\WorkingForumBundle\Entity\UserInterface in your user entity. Then copy/paste the content of \Yosimitso\WorkingForumBundle\Entity\User (attributes, getter, setter) into your user entity.
I'll update the readme about this point and i'll try to find a better solution to work with fosuserbundle

**Comment by napestershine** [comment]
@Yosimitso  Thanks :)
