### ISSUE TITLE
Impossible to add forum

### ISSUE THREAD

**Issue by antittrust** [Yosimitso/WorkingForumBundle#19]
Salut je vien juste de finir d'installer ce bundle ensuivant la doc tout fonctionne bien mais j'obtiens cette erreur quand j'essaie d'ajouter un forum

> Attempted to load class "ArrayCollection" from the global namespace.
Did you forget a "use" statement for "Doctrine\Common\Collections\ArrayCollection"?

Stack Trace
in vendor\yosimitso\workingforumbundle\Entity\Subforum.php at line 103   -
    } 
    public function __construct() { 
        $this->allowedRoles = new \ArrayCollection; 
    } 
    /** 

de plus c'est bien app/YosimitsoWorkingForumBundle/views pour surcharger les vue?

**Comment by Yosimitso** [comment]
Salut, désolé effectivement il y a une erreur, un antislash en trop. J'ai corrigé et si tu récupères la dernière version de master tu n'auras plus le problème. Pour surcharger les vues tu dois ajouter les fichiers dans  : app\Resources\YosimitsoWorkingForumBundle\views

**Comment by antittrust** [comment]
Pas de souci ça fonctionne bien par contre je retombe sur 2 autre souci l'ajout de nouveaux sujet renvoi sur une autre erreur

``Cannot read index "content" from object of type "Yosimitso\WorkingForumBundle\Entity\Post" because it doesn't implement \ArrayAccess.

et le lien pour l'ajout de sous-forum ne fonctionne pas en 3.2 j'ai ce message dans le profiler

``User Deprecated: Call Form::isValid() with an unsubmitted form is deprecated since version 3.2 and will throw an exception in 4.0. Use Form::isSubmitted() before Form::isValid() instead.

**Comment by Yosimitso** [comment]
Ca a l'air d'être lié a la version 3.2 de symfony, je vais passer la démo à cette version pour mettre à jour le bundle ca ne doit pas être grand chose ;)

**Comment by antittrust** [comment]
C'est ce que je me suis dit en voyant les erreurs ^^

**Comment by Yosimitso** [comment]
Corrigé :)
