### ISSUE TITLE
ornj/markdown-bundle is it essential?

### ISSUE THREAD

**Issue by napestershine** [Yosimitso/WorkingForumBundle#2]
Every time when I try to install this bundle I get error to have to ornj/markdown-bundle it first.

**Comment by Yosimitso** [comment]
What kind of error ? Try the version 1.5
This bundle is essential to render posts

**Comment by napestershine** [comment]
It do not install automatically, so I think you should add this also in readme for installation

**Comment by Yosimitso** [comment]
Sorry i read too fast, i was talking about Knp/MarkdownBundle.
I will remove ornj/markdown-bundle from the composer,that was a test, but as written in the readme you only need Knp/PaginatorBundle et Knp/MarkdownBundle for my bundle

**Comment by napestershine** [comment]
Thanks :+1:
