### ISSUE TITLE
Changing parameters in URL

### ISSUE THREAD

**Issue by gaeljacquin** [Yosimitso/WorkingForumBundle#22]
Hello,

When I pass `thread.subforum.id` instead of `thread.subforum.slug` as the `subforum_slug` in index.html.twig (and the other relevant twig files), the URLs change accordingly but then clicking on the subforum then returns the following:

`Error: Call to a member function getAllowedRoles() on null
`

And this line is highlighted:

`110. $subforumRoles = $subforum->getAllowedRoles();
`

Same thing happens when I replace 'view' with '{view}' in routing.yml (so that 'view' can be translated per the user's locale), though only the Admin section returns the above error in this case. 

Any help is appreciated!

**Comment by gaeljacquin** [comment]
I fixed it!

I changed the way slugs are constructed in the controller, and added "@Route("/forum/view/")" in the annotations to enable slug localization.

**Comment by Yosimitso** [comment]
Hi
sorry i didn't see your message but i'm glad you made it
Translate the routing is indeed a good idea !

**Comment by gaeljacquin** [comment]
No worries!

I couldn't quite figure out what getAllowedRoles had to do with anything or what "a:1:{i:0;s:0:"";}" in the allowed_roles field means though.

**Comment by Yosimitso** [comment]
allowedRoles is an array in the db, so the orm will always casted it (serialize) as array even if it's empty ;)
