### ISSUE TITLE
User can upload images

### ISSUE THREAD

**Issue by napestershine** [Yosimitso/WorkingForumBundle#27]
HI

Adding new feature of uploading picture through upload will be much better, instead of link. It will help a lot.

TIA

**Comment by Yosimitso** [comment]
Hi
Yeah it would be great ! It's a big feature, I'll add it to todo

**Comment by Yosimitso** [comment]
This feature will be available soon ! The branch fileupload-system will be in test on the demo forum in a few days

**Comment by napestershine** [comment]
@Yosimitso 

Thanks you so much.

**Comment by Yosimitso** [comment]
You can test the feature on the demo board :)
http://demo.charlymartins.fr/demoworkingforum/
