### ISSUE TITLE
update Readme.md please

### ISSUE THREAD

**Issue by DmytroSolodukhin** [Yosimitso/WorkingForumBundle#29]
Hellow.
Could you please update you documentation to install your bundle, it's interesting project for me.

**Comment by Yosimitso** [comment]
Sure ! But on which part are you stuck?

**Comment by DmytroSolodukhin** [comment]
I have already installed everything, but it would be nice to describe the routes in the description, and the interaction with your methods

**Comment by Yosimitso** [comment]
For importing the bundle's routes you need to add in your config\routing.yml (sorry the markdown rendering is not good);
`yosimitso_working_forum:
    resource: "@YosimitsoWorkingForumBundle/Resources/config/routing.yml"
    prefix:   /`
You are free to change the prefix
And I can add some comments in the routing if it's what you mean
