### ISSUE TITLE
Exception when I run

### ISSUE THREAD

**Issue by napestershine** [Yosimitso/WorkingForumBundle#3]
HI

When I try to run I am getting error:

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
The child node "allow_anonymous_read" at path "yosimitso_working_forum" must be configured.

**Comment by napestershine** [comment]
Fixed above by assigning a node with true value.

Got another one;
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  The child node "allow_moderator_delete_thread" at path "yosimitso_working_forum" must be configured.

**Comment by napestershine** [comment]
I got message for YAML deprecation in config.yml for unquoted colon values in sf3.

**Comment by Yosimitso** [comment]
Hi
Sorry I forgot to update the readme about the config. Here's the missing config keys:
    allow_anonymous_read: false
    allow_moderator_delete_thread: false

**Comment by napestershine** [comment]
okay thanks. Do  I have to put values in quotes? If you have checked my last comment

**Comment by Yosimitso** [comment]
No only the key date_format needs quotes to escape colons.
It's weird because i have SF3 too and i have no deprecation notice

**Comment by napestershine** [comment]
I will check it again :+1:  Thanks
