### ISSUE TITLE
Support for Symfony 4

### ISSUE THREAD

**Issue by napestershine** [Yosimitso/WorkingForumBundle#33]
Hi
Do it support Symfony 4?

TIA

**Comment by Yosimitso** [comment]
Hi
Currently the bundle is not compatible with Sf4, but I started to work a week ago on the migration of the demo board and the bundle. I've created a branch "v4" yesterday to test it

**Comment by napestershine** [comment]
@Yosimitso  That's awesome.

**Comment by Yosimitso** [comment]
It's almost done :) 
The branch 'sf4' contains the bundle compatible with Symfony 4 AND Symfony 3, I tested it with my local application on Sf4 and we need to test it on the demo board which is running sf 3.4
I'd like to migrate the application (not the bundle) to Flex after the compatibility tests

**Comment by napestershine** [comment]
Okay, Thanks @Yosimitso  :)

Can you please add some instructions on how to install that sf4 branch?
And how can I add more functionality to bundle and send a pull request, kind of contribution guide ?

Thanks

**Comment by Yosimitso** [comment]
I'm still working on the bundle, I saw that the bundle could be compatible with Sf4 and not compatible with Sf4 with Flex... I hope that the modifications for Flex won't break the bundle's compatibility with Sf3 ! I'll add a branch sf4-flex in case of breaking changes and I'll test again everything

To test the branch add to your composer.json
`"yosimitso/workingforumbundle" : "dev-sf4"`

Yeah I know I should write a contribution guide :D and i will do it, but you can still send a pull request using the "standard" guideline. I'm happy when people wants to contribute so go for it :P

**Comment by napestershine** [comment]
I am not sure about the installation of bundle in sf4, just following some steps. 

added in composer, then added 3 other dependencies in composer.

Added it in `composer.json'
```
    "yosimitso/workingforumbundle": "dev-sf4",
    "knplabs/knp-paginator-bundle": "~2.5",
    "knplabs/knp-markdown-bundle": "~1.5",
    "sensio/framework-extra-bundle": "~3.0"
```

and when I do composer update
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)

Prefetching 2 packages
  - Downloading (100%)

Package operations: 0 installs, 2 updates, 0 removals
  - Updating symfony/dependency-injection (v4.0.4 => v3.4.4): Loading from cache
  - Updating sensio/framework-extra-bundle (v3.0.27 => v3.0.29): Loading from cache
Writing lock file
Generating autoload files

What about running composer thanks now?
This will spread some love by sending a star to the GitHub repositories of your fellow package maintainers.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 32:                                                                                                                                                                                           
!!    The service "knp_paginator.helper.processor" has a dependency on a non-existent service translator".
!!                                                                                                                                                                                           
!!
!!

```

**Comment by Yosimitso** [comment]
Sf4 is a microframework now and a lot of packages aren't installed by default, and it seems that this version of knp-paginator doesn't require all dependencies needed
I'll see if the forum neeeds a higher version of this bundle
But you can fix easily the problem with a `composer require translator` :+1: 
You might have other missing dependencies but it shoud easy to fix, just 'require' the needed packages

**Comment by napestershine** [comment]
Okay. I am trying to make it work again! Thanks so much.
