### ISSUE TITLE
[Bug] Error while adding a new forum

### ISSUE THREAD

**Issue by Clowrid** [Yosimitso/WorkingForumBundle#35]
New bug since refracto : https://github.com/Yosimitso/WorkingForumBundle/commit/138de129493d2a7f30562bd4fb008ac492e87bf4

Adding a new forum throw this validation error :
![image](https://user-images.githubusercontent.com/4417026/37290025-81bf0c42-260b-11e8-9ad3-45dd219e2daf.png)

I'm doing a quick pull request to disable the validation

**Comment by Yosimitso** [comment]
Thanks ! I'm currently working on functionnal tests to avoid this kind of problem
