### ISSUE TITLE
[Bug] New thread - pin error

### ISSUE THREAD

**Issue by Clowrid** [Yosimitso/WorkingForumBundle#37]
since refacto : https://github.com/Yosimitso/WorkingForumBundle/commit/138de129493d2a7f30562bd4fb008ac492e87bf4

When adding a new thread :

> Neither the property "pin" nor one of the methods "pin()", "getpin()"/"ispin()"/"haspin()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView".

I looked at the code, there are two errors:

- A wrong variable sent to the embed : https://github.com/Yosimitso/WorkingForumBundle/blob/master/Resources/views/Thread/new.html.twig#L53  : 'form': form.post.0 ( form.pin is in the root form, not in form.post.0 )
- A logic error. The goal is to hide the "pin" button when the user does not have the ROLE_ADMIN. But because of the function "{{form_rest (form)}}" it will always be displayed. We need to manage this in the ThreadFormType.

I will try to submit a pull request quickly.

**Comment by Yosimitso** [comment]
Hi
I'm working on the branch sf4-flex for a few weeks and I've already fixed some stuffs, I've merged this branch into master to avoid future conflict with your work, can you pull master and rebase your branch on master ? And then I take look on your work, thakns again ! :)

**Comment by Clowrid** [comment]
Sure. Does this version works with SF3.4 ?
When i try to use it on my project (3.4) i got this error : 

> yosimitso/workingforumbundle dev-master requires symfony/framework-bundle ~4.0 -> satisfiable by symfony/framework-bundle[v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6].
>     - don't install symfony/framework-bundle v4.0.0|don't install symfony/symfony v3.4.0

**Comment by Yosimitso** [comment]
Yeah it works with 3.4 but I modified the composer.json to test the dependencies with Sf4, I have to lower the versions needed now
