### ISSUE TITLE
Mapping issue with post and user entities 

### ISSUE THREAD

**Issue by Mradhamdi** [Yosimitso/WorkingForumBundle#43]
after configuring the bundle , a problem occured with the mappingbetween post and user entities 
"  Column name `id` referenced for relation from Yosimitso\WorkingForumBundle\Entity\Post towards AppBundle\Entity\User does not exist. " 
Please help it's urgent

**Comment by Yosimitso** [comment]
Can you show your user entity? It seems that  the main property (id) is missing

**Comment by Mradhamdi** [comment]
thank you for repling,
i'v just extended \Yosimitso\WorkingForumBundle\Entity\User , and i added this  to link the user with th post :
/**
     * @ORM\OneToMany(targetEntity="Yosimitso\WorkingForumBundle\Entity\Post", mappedBy="user")
     * @ORM\JoinColumn(name="post_id", referencedColumnName="id", nullable=true)
     */
    private $post;

    /**
     * @return mixed
     */
    public function getPost()
    {
        return $this->post;
    }

    /**
     * @param mixed $post
     */
    public function setPost(Post $post)
    {
        $this->post = $post;
    }

**Comment by Yosimitso** [comment]
You don't need to define oneToMany relations with WorkingForum entities, into your own user entity
Just extends \Yosimitso\WorkingForumBundle\Entity\User and put what you need for your application
And in your doctrine.yaml
`resolve_target_entities:
    Yosimitso\WorkingForumBundle\Entity\User: You\YourUserBundle\Entity\YourUser`

**Comment by Mradhamdi** [comment]
thank you it works

**Comment by Yosimitso** [comment]
Good ! Don't forget to star the repo if you like it ;)
