### ISSUE TITLE
stuck on this error after install : Call to a member function has() on null

### ISSUE THREAD

**Issue by 3rw1n** [Yosimitso/WorkingForumBundle#44]
Hi,

I just installed this bundle on symfony 3.4.
I followed your install instructions but I'm now stuck on this error when I try to reach the bundle's main "workingforum_forum" route=>

`Call to a member function has() on null`

Here's the full stack trace =>

```
Symfony\Component\Debug\Exception\FatalThrowableError:
Call to a member function has() on null

  at vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\ControllerTrait.php:283
  at Symfony\Bundle\FrameworkBundle\Controller\Controller->render('@YosimitsoWorkingForum/Forum/index.html.twig', array('list_forum' => array()))
     (vendor\yosimitso\workingforumbundle\Controller\ForumController.php:32)
  at Yosimitso\WorkingForumBundle\Controller\ForumController->indexAction()
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web\app_dev.php:30)
```

Any idea what I'm doing wrong ?
Thanks in advance !

Cheers,
Erwin

**Comment by Yosimitso** [comment]
Hi
This issue seems to be related to your template engine, it's hard to say what's wrong but maybe the framework doesn't understand the @YosimitsoWorkingForum but I can't say why with this stracktrace
Check if you have this in your config : 
```
framework:
    templating:
        engines: twig
```

Try to upgrade twig and symfony if you can
Hope this help

**Comment by Yosimitso** [comment]
I checked Symfony files and it seems like your template engine is not registered as a service
Does your application works outside the bundle ?

**Comment by 3rw1n** [comment]
Hi
Besides this bundle everything works fine.
I checked my config and it's set right.

I also updated symfony & twig with nos result.

```
"symfony/symfony": "~3.4",
"twig/extensions": "~1.5",
"twig/twig": "~2.0", 
```

**Comment by Yosimitso** [comment]
Weird !
I planned to inject the templating engine into the base controller, maybe it will help to find out the error
I'll warn you on this thread when it's done

**Comment by 3rw1n** [comment]
Ok, thanks !

**Comment by Yosimitso** [comment]
Can you try to swicth to the branch "templating-dependency" ?
In your composer : 
`"yosimitso/workingforumbundle" : "dev-templating-dependency"`

With this branch, I think the error will be easier to resolve if your application fails on the dependency injection

**Comment by roldan** [comment]
Hi @Yosimitso ,

I'm facing the same issue as @3rw1n . As a workaround I'm adding "@service_container" in setParameter "calls" for service "yosimitso_workingforum_base_controller".

services.yml
```
yosimitso_workingforum_base_controller:
        class: Yosimitso\WorkingForumBundle\Controller\BaseController
        calls:
          - ["setParameters",["@service_container", "@doctrine.orm.entity_manager","@yosimitso_workingforum_authorization","@=service('security.token_storage').getToken().getUser()","@session", "@translator", "@knp_paginator"]]
```
BaseController.php
```
<?php

namespace Yosimitso\WorkingForumBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Yosimitso\WorkingForumBundle\Security\Authorization;

/**
 * Class BaseController
 *
 * @package Yosimitso\WorkingForumBundle\Controller
 */
class BaseController extends Controller
{
    protected $em;
    protected $authorization;
    protected $user;
    protected $flashbag;
    protected $translator;
    protected $paginator;
    protected $container;

    public function setParameters($container, $em, $authorization, $user, $session, $translator, $paginator) {
        $this->container = $container;
        $this->em = $em;
        $this->authorization = $authorization;
        $this->user = (is_object($user)) ? $user : null;
        $this->flashbag = $session->getFlashBag();
        $this->translator = $translator;
        $this->paginator = $paginator;

    }
}
```
Anyway I'm not being able to override twig templates. I'm using a custom bundle with 'getParent' implented returning 'YosimitsoWorkingForumBundle'. It's strange beacuse I'm also overriding translations and it works fine. Any hint of why this could be happening?

Thanks,
Matías

**Comment by Yosimitso** [comment]
Hi
I see that you have the previous version of the bundle
The fix is merged into master and included and the 2.0 version
Try to switch branch/release in your composer.json that should work :)
To override templates, the path depends to your symfony version : 
for sf4 : templates/bundles/YosimitsoWorkingForumBundle/thefiletooverride.html.twig
for sf3 : app/Resources/YosimitsoWorkingForumBundle/views/****

**Comment by roldan** [comment]
Hi,

thanks for answering! I'm using Symfony 2.8.9. It's ok with using 2.0 tag?

Thanks!
Matías

**Comment by Yosimitso** [comment]
Sorry I can't be sure I don't have project on sf2 anymore
But just give a try on your dev env with the 2.0 you'll see immediately

**Comment by Yosimitso** [comment]
@roldan is it ok for you?

**Comment by roldan** [comment]
Sorry @Yosimitso , I couldn't try it yet.. I'll check 2.0 branch tomorrow and get back to you, thanks !
