### ISSUE TITLE
strpos() error when I run initial setup with Flex structure

### ISSUE THREAD

**Issue by marsender** [Yosimitso/WorkingForumBundle#46]
Hi,
I've created a new Symfony flex app.
When I run the setup for Symfony 4 with Flex structure command:
composer require yosimitso/workingforumbundle : ~1.2.4
I get this error:
[ErrorException] strpos(): Empty needle
Thanks

**Comment by Yosimitso** [comment]
Hey
Try this command that should work 
```
composer require "yosimitso/workingforumbundle":"~1.2.4"
```

**Comment by marsender** [comment]
Oh thanks. Perfect.
Could you please correct this info in your SETUP-SF4-FLEX.md instructions.

**Comment by Yosimitso** [comment]
You're right thanks for noticing
