### ISSUE TITLE
Improve Demo

### ISSUE THREAD

**Issue by wetternest** [Yosimitso/WorkingForumBundle#5]
Hi!
Please add an admin-account and an moderator-account to test at your demo-board!
thx!

**Comment by Yosimitso** [comment]
I've created a moderator account, the username and the password are in the header.
I won't provide the admin password for the moment, i don't want that demo to be a mess but I'll made screenshots

**Comment by wetternest** [comment]
you could just reset the database every hour or so. if someone messes up after an hour its gone

**Comment by napestershine** [comment]
:+1:  a cron job should do it

**Comment by Yosimitso** [comment]
Sure why not ! I'll see what I can do :+1:

**Comment by wetternest** [comment]
(y) fine! looking forward to it!
