### ISSUE TITLE
Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of '256' reached, aborting! in /var/www/html/pca/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/Driver/SymfonyFileLocator.php:62

### ISSUE THREAD

**Issue by Topheur** [Yosimitso/WorkingForumBundle#51]
Hello,

I follow the SETUP-SF2-SF3.md documentation to install the forum and I have the error :
`Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of '256' reached, aborting! in /var/www/html/pca/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/Driver/SymfonyFileLocator.php:62
`
In the stack trace, I see that it goes by : 
`#3 /var/www/html/pca/var/cache/dev/ContainerPeanjek/appDevDebugProjectContainer.php(4907): ContainerPeanjek\appDevDebugProjectContainer->getYosimitsoWorkingforumUtilSubscriptionService()`
or
`#3 /var/www/html/pca/var/cache/dev/ContainerFtkxdwy/appDevDebugProjectContainer.php(4934): ContainerFtkxdwy\appDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService()`

I have Symfony 3.4, workingforumbundle V2.0.

At this moment, I just registered the bundle in AppKernel and put the config in config.yml.

Feel free to ask I you want more details ;)

Thanks

**Comment by Topheur** [comment]
This is a part of the full stack trace with the repetition :

```
at appDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService()in appDevDebugProjectContainer.php line 4934
at appDevDebugProjectContainer->getYosimitsoWorkingforumUtilSubscriptionService()in appDevDebugProjectContainer.php line 4904
at appDevDebugProjectContainer->getYosimitsoWorkingforumListener_PostService()in appDevDebugProjectContainer.php line 1957
at appDevDebugProjectContainer->getDoctrine_Dbal_DefaultConnectionService()in appDevDebugProjectContainer.php line 2020
at appDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService()in appDevDebugProjectContainer.php line 4934
at appDevDebugProjectContainer->getYosimitsoWorkingforumUtilSubscriptionService()in appDevDebugProjectContainer.php line 4904
at appDevDebugProjectContainer->getYosimitsoWorkingforumListener_PostService()in appDevDebugProjectContainer.php line 1957
at appDevDebugProjectContainer->getDoctrine_Dbal_DefaultConnectionService()in appDevDebugProjectContainer.php line 2020
at appDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService()in Container.php line 306
```

**Comment by Yosimitso** [comment]
Hi,
I think it's an error related to xdebug configuration, try to increase the value 'nesting level' or just deactivate xdebug and you will get the 'true' error
Have you made the doctrine schema update ?

**Comment by Topheur** [comment]
I put 1024, I have the same error. If I desactivate it, the application freezes.
No I can't make the doctrine schema update because I have the same error on CLI.

**Comment by Yosimitso** [comment]
what do you mean by freeze ?

**Comment by Topheur** [comment]
In putty I can't write any command and my browser try to load. Oblige to restart Apache :(

**Comment by Yosimitso** [comment]
xdebug crash may broke everything, restart, clear cache
The stack trace seems to show an doctrine problem

**Comment by Topheur** [comment]
Yes : first it tries to get default_entity_manager by calling getDoctrine_Dbal_DefaultConnectionService.
This will call getYosimitsoWorkingforumListener_PostService and after getYosimitsoWorkingforumUtilSubscriptionService.
But getYosimitsoWorkingforumUtilSubscriptionService need default_entity_manager...

**Comment by Yosimitso** [comment]
Do you use Doctrine on your project ? The bundle use the service doctrine.entity_manager defined by doctrine

**Comment by Topheur** [comment]
Yes I use Doctrine.
When I comment the definition of the service yosimitso_workingforum_listener.post in services.yml it's work.

**Comment by Topheur** [comment]
Anyway after I have the problem that Class "yosimitso_workingforum_forum_controller" does not exist...
I think I have a big problem on my code with services...

**Comment by Topheur** [comment]
I see in the documentation that the version is 1.2.4 :
`composer require "yosimitso/workingforumbundle":"~1.2.4"`
Maybe i need to downgrade to 1.2.4 ? Because i have the V2

**Comment by Yosimitso** [comment]
Yes i think that the bundle isn't properly loaded by your application
Try to run `php bin/console debug:container` you have to see services like yosimitso_workingforum_*
Controllers are defined as services even on the 1.2.4 so keep the 2.0 :)

**Comment by Topheur** [comment]
Finally I downgrade to 1.2.4... and it works ;) Like i said you I have the impression that I have an error about new services that you put in V2.

**Comment by Yosimitso** [comment]
Ok that's a solution :D
So it's maybe related to the doctrine event listener, entity have lifecycle callback in the 2.0
What is your doctrine's version ? on the demo it's 
````
doctrine/doctrine-bundle:1.10.0
doctrine/common:2.10.0
````
