### ISSUE TITLE
Class "yosimitso_workingforum_forum_controller" does not exist.

### ISSUE THREAD

**Issue by issambaccouch** [Yosimitso/WorkingForumBundle#52]
Hi i am new with symfony i use symfony 3.4 i do everything in setup file but in step six i put the code in routing.yml instead config.yml to solve prefix issue but i get that error , any help plz ?

**Comment by Yosimitso** [comment]
Hello
Seems like the bundle isn't loaded, have you add it into your appKernel?

**Comment by issambaccouch** [comment]
Hello , yes i did follow all the steps in the setup file , also i cleared the cache too and update the composer and i did the dump-auto-load but still not working i just change the route from / to /forum

**Comment by Yosimitso** [comment]
Do you see the bundle loaded in the profiler ? And with the command debug:container ? 
Are you using the version 2.0 ?

**Comment by issambaccouch** [comment]
yes i use v2 of the bundle also when i run command debug:container the bundle is loaded but in the profile i get this error "Token "XXXXX" was not found in the database."  , i use FOSuser

**Comment by Yosimitso** [comment]
It means the debug token from cache is missing
 if you always see this message it means you have a problem in your application and it's not bundle related
You can also try to downgrade to v1.2.4

**Comment by Yosimitso** [comment]
@issamsolid I found your issue on 3.4 about your error I will issue a release to fix it
