### ISSUE TITLE
Error on new thread with file size

### ISSUE THREAD

**Issue by yotoya** [Yosimitso/WorkingForumBundle#62]
I have problems with adding new thread. 
Util/FileUploader in method extractSize(). My value is 40M and I'm getting array:
`array:3 [
  0 => "4",
  1 => "4",
  2 => ""
]`
Position 2 exist, but it's empty.

**Comment by Yosimitso** [comment]
Hi,
Sorry for that, a contributor has identified the bug and his PR https://github.com/Yosimitso/WorkingForumBundle/pull/59 will fix it
I'll merge it in a couple of hours and draft a minor version

**Comment by Yosimitso** [comment]
it's done you can use the v2.0.2

**Comment by yotoya** [comment]
Checked. It's working, thanks.
