### ISSUE TITLE
SwiftmailerBundle is now obsolete

### ISSUE THREAD

**Issue by Anyeos** [Yosimitso/WorkingForumBundle#81]
As you can look at: https://symfony.com/doc/current/reference/configuration/swiftmailer.html

> Caution
> 
> The Swift Mailer project is not supported since November 2021 and its integration with Symfony was removed in Symfony 6.0.
> 
> Use the Symfony Mailer component, which was introduced in Symfony 4.3 as a modern replacement of Swift Mailer.

I suggest change to "Symfony Mailer" as replacement. Actually is what I am using on all my projects.

**Comment by Yosimitso** [comment]
Thanks for noticing, I'll update this dependency!

**Comment by Ricardo57100** [comment]
Hello,

Any idea of when the dependency will be updated ?

Thanks in advance.

**Comment by Yosimitso** [comment]
Hi,
It's coming soon 
I'm working on it, I have to test it now

**Comment by Yosimitso** [comment]
@Anyeos @Ricardo57100 
if you've got time can you test with 
`composer require yosimitso/workingforumbundle:dev-mailer`

and add `MAILER_DSN=smtp://user:pass@smtp.example.com` in your .env.local

**Comment by Ricardo57100** [comment]
Hi,

Thanks for your quick reply, it seems to work now.

Thanks a lot :)

**Comment by Yosimitso** [comment]
fixed in #82
