### ISSUE TITLE
Post content : allow HTML

### ISSUE THREAD

**Issue by Ricardo57100** [Yosimitso/WorkingForumBundle#83]
Hi,

Is it possible to have a meaning to have the control on post content stored in database ?

I'm using ckeditor for post content and I would like to avoid the call of 'strip_tags' method before saving content on database (i want to use base64_encode instead).

Maybe define Post entity as a superclass ?

Thanks in advance for you reply.

**Comment by Yosimitso** [comment]
Hello,
I didn't plan to have different version of syntax for post, but I think it would be much easier for you to use ckeditor with the markdown plugin, with this solution maybe you'll just have to override the template to achieve it

**Comment by Ricardo57100** [comment]
Hello, thanks for the advice, i will go on with it.
