### ISSUE TITLE
sf6.4 which version of bundle?

### ISSUE THREAD

**Issue by vtuz** [Yosimitso/WorkingForumBundle#86]
Hi! 
Which version of bundle should be used to satisfy all dependencies for symfony 6.4?
Installed the default sf6 (using symfony new --webapp forum --version=6.4) and getting dependencies errors when run: 
`composer require "yosimitso/workingforumbundle"`. Tried different versions, "^5", "sf6-dev"

**Comment by Yosimitso** [comment]
Hi
Yesterday I merged my work for Sf6 compatibility on master, but there is no release yet

So you can use dev-master
